before_install:
    sudo apt-get install automake autotools-dev gcc make autoconf yasm nasm git wget curl libtool g++ libboost-all-dev

notifications:
    email:
        recipients:
            - cvetomirdenchev@gmail.com
        on_success: always
        on_failure: always

branches:
    only: ["console-application"]

language: cpp

script:
    make release
