before_install:
    sudo apt-get install automake autotools-dev gcc make autoconf yasm nasm git wget curl libtool g++ libboost-all-dev

notifications:
    email:
        recipients:
            - cvetomirdenchev@gmail.com
        on_success: always
        on_failure: always

branches:
    only: ["console-application"]

language: cpp

matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-6
          env:
              - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

script:
    make release
