######################################################################
# Automatically generated by qmake (3.0) Thu Apr 12 17:37:07 2018
######################################################################

TEMPLATE = app
TARGET = spooky2-database-analyser
INCLUDEPATH += .

# Input
HEADERS += include/s2dbanalyser.h include/Spooky2DatabaseAnalyser.h
SOURCES += main.cpp src/s2dbanalyser.cpp src/Spooky2DatabaseAnalyser.cpp
